In [1]:
import numpy as np

In [2]:
data = np.loadtxt(r'D:\Educational(B.E.)\Course\Data_Mining\Learning-Python-master\affinity_dataset.txt')

In [3]:
data

array([[0., 0., 1., 1., 1.],
       [1., 1., 0., 1., 0.],
       [1., 0., 1., 1., 0.],
       [0., 0., 1., 1., 1.],
       [0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 1., 1., 1.],
       [1., 1., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 1.],
       [0., 1., 0., 0., 1.],
       [0., 0., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [0., 0., 1., 1., 1.],
       [1., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 1.],
       [0., 0., 1., 1., 1.],
       [0., 0., 1., 1., 0.],
       [0., 0., 1., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 1., 0.],
       [1., 1., 1., 0., 1.],
       [1., 1., 0., 0., 1.],
       [0., 0., 1., 1., 1.],
       [0., 0., 1., 0., 1.],
       [0., 0.

In [4]:
n_samples, n_features = data.shape

In [5]:
print(data[:5])

[[0. 0. 1. 1. 1.]
 [1. 1. 0. 1. 0.]
 [1. 0. 1. 1. 0.]
 [0. 0. 1. 1. 1.]
 [0. 1. 0. 0. 1.]]


In [6]:
# The names of the features, for your reference.
features = ["bread", "milk", "cheese", "apples", "bananas"]

In [7]:
# First , how many rows contain our premise: that a person is buying apples 
num_apples_purchases = 0
for sample in data:
    if sample[3] == 1: # This person bought Apples
        num_apples_purchases += 1
print("{0} people bought Apples".format(num_apples_purchases))
        

36 people bought Apples


In [8]:
# Simply if we want banana and index value is 4
num_banana_purchases = 0
for sample in data:
    if sample in data:
        if sample[4] == 1: # This person bought Banana
            num_banana_purchases += 1
print("{0} people bought Banana".format(num_banana_purchases))
        

59 people bought Banana


In [9]:
# How many of the cases that a person bought Apple involved the people purchasing banabas to?
#Record both cases where thr ulr is valid and is invalid
rule_valid = 0
rule_invalid = 0

for sample in data:
    if sample[3] == 1: # Person bought Apples
        if sample[4] == 1: # This person bought banana
            rule_valid += 1
        else:
            rule_invalid += 1
print("{0} cases of the being valid were discovered".format(rule_valid))
print("{0} cases of thr being invalid were discovered". format(rule_invalid))
        

21 cases of the being valid were discovered
15 cases of thr being invalid were discovered


In [10]:
# Now we have all the information neede to compute support and confidance
support = rule_valid# The support is the number of times the rule is discovered
confidence = rule_valid/ num_apples_purchases
print("The support is {0} and the confidance is {1:.3f}".format(support, confidence))
print("As a percenatage , that is {0:.1f}%".format(100*confidence))

The support is 21 and the confidance is 0.583
As a percenatage , that is 58.3%


In [11]:
from collections import defaultdict

In [14]:
valid_rules = defaultdict(int)
invalid_rules = defaultdict(int)
num_occurences = defaultdict(int)

In [15]:
for sample in data:
    for premise in range(n_features):
        if sample[premise] == 0: continue
        # Record that the premise was bought in another transaction
        num_occurences[premise] += 1
        for conclusion in range(n_features):
            if premise == conclusion:  # It makes little sense to measure if X -> X.
                continue
            if sample[conclusion] == 1:
                # This person also bought the conclusion item
                valid_rules[(premise, conclusion)] += 1
            else:
                # This person bought the premise, but not the conclusion
                invalid_rules[(premise, conclusion)] += 1
support = valid_rules
confidence = defaultdict(float)
for premise, conclusion in valid_rules.keys():
    confidence[(premise, conclusion)] = valid_rules[(premise, conclusion)] / num_occurences[premise]

In [16]:
for premise, conclusion in confidence:
    premise_name = features[premise]
    conclusion_name = features[conclusion]
    print("Rule: If a person buys {0} they will also buy {1}".format(premise_name, conclusion_name))
    print(" - Confidence: {0:.3f} %".format(100*confidence[(premise, conclusion)]))
    print(" - Support: {0}".format(support[(premise, conclusion)]))
    print("")

Rule: If a person buys cheese they will also buy apples
 - Confidence: 60.976 %
 - Support: 25

Rule: If a person buys cheese they will also buy bananas
 - Confidence: 65.854 %
 - Support: 27

Rule: If a person buys apples they will also buy cheese
 - Confidence: 69.444 %
 - Support: 25

Rule: If a person buys apples they will also buy bananas
 - Confidence: 58.333 %
 - Support: 21

Rule: If a person buys bananas they will also buy cheese
 - Confidence: 45.763 %
 - Support: 27

Rule: If a person buys bananas they will also buy apples
 - Confidence: 35.593 %
 - Support: 21

Rule: If a person buys bread they will also buy milk
 - Confidence: 51.852 %
 - Support: 14

Rule: If a person buys bread they will also buy apples
 - Confidence: 18.519 %
 - Support: 5

Rule: If a person buys milk they will also buy bread
 - Confidence: 30.435 %
 - Support: 14

Rule: If a person buys milk they will also buy apples
 - Confidence: 19.565 %
 - Support: 9

Rule: If a person buys apples they will also bu

**Now we have a dictionary that support and confidance ofr each rule** 

In [25]:
def print_rule(premise, conclusion,support, confidence, features):
    premise_name = features[premise]
    conclusion_name = features[conclusion]
    print("Rule: If a person buy {0} they will also buy {1} ".format(premise_name, conclusion_name))
    print("- Support: {0} ".format(support[(premise, conclusion)]))
    print("- Confidance: {0:.3f} %".format(100* confidence[(premise, conclusion)]))

In [26]:
premise = 1
conclusion = 3
print_rule(premise, conclusion, support, confidence , features)

Rule: If a person buy milk they will also buy apples 
- Support: 9 
- Confidance: 19.565 %


In [31]:
premise = 2
conclusion =3
print_rule(premise, conclusion, support, confidence, features)

Rule: If a person buy cheese they will also buy apples 
- Support: 25 
- Confidance: 60.976 %


In [32]:
premise = 3
conclusion =2
print_rule(premise, conclusion, support, confidence, features)

Rule: If a person buy apples they will also buy cheese 
- Support: 25 
- Confidance: 69.444 %


In [34]:
premise = 4
conclusion =1
print_rule(premise, conclusion, support, confidence, features)

Rule: If a person buy bananas they will also buy milk 
- Support: 19 
- Confidance: 32.203 %


In [35]:
premise = 2
conclusion =0
print_rule(premise, conclusion, support, confidence, features)

Rule: If a person buy cheese they will also buy bread 
- Support: 4 
- Confidance: 9.756 %


# Ranking to find the best rules

In [36]:
from operator import itemgetter

In [38]:
sorted_support = sorted(support.items(), key=itemgetter(1), reverse=True)

In [44]:
for index in range(5):
    print("Rule #{0}".format(index + 1))
    
    premise, conclusion = sorted_support[index][0]
    print_rule(premise, conclusion, support, confidence, features)
    print("")

Rule #1
Rule: If a person buy cheese they will also buy bananas 
- Support: 27 
- Confidance: 65.854 %

Rule #2
Rule: If a person buy bananas they will also buy cheese 
- Support: 27 
- Confidance: 45.763 %

Rule #3
Rule: If a person buy cheese they will also buy apples 
- Support: 25 
- Confidance: 60.976 %

Rule #4
Rule: If a person buy apples they will also buy cheese 
- Support: 25 
- Confidance: 69.444 %

Rule #5
Rule: If a person buy apples they will also buy bananas 
- Support: 21 
- Confidance: 58.333 %



In [49]:
sorted_confidence = sorted(confidence.items(), key=itemgetter(1), reverse=True)

In [51]:
for index in range(5):
    print("Rule %{0}",format(index + 1))
    premise, conclusion = sorted_confidence[index][0]
    print_rule(premise, conclusion, support, confidence, features)
    print("")

Rule %{0} 1
Rule: If a person buy apples they will also buy cheese 
- Support: 25 
- Confidance: 69.444 %

Rule %{0} 2
Rule: If a person buy cheese they will also buy bananas 
- Support: 27 
- Confidance: 65.854 %

Rule %{0} 3
Rule: If a person buy bread they will also buy bananas 
- Support: 17 
- Confidance: 62.963 %

Rule %{0} 4
Rule: If a person buy cheese they will also buy apples 
- Support: 25 
- Confidance: 60.976 %

Rule %{0} 5
Rule: If a person buy apples they will also buy bananas 
- Support: 21 
- Confidance: 58.333 %

